# Numpy Assignment

### Task 1 Creating NumPy Arrays

In [ ]:
'''
1. import numpy as np
2. create the following arrays:
    a 1d array in integers from 1 to 10
    a 2d array of shape (3,3) with values from 1 to 9
    a numpy array from the list [10, 20, 30, 40, 50]

3. Print:
    Shape of each array
    Data type of each array
'''

In [23]:
import numpy as np

array1=np.array([1,2,3,4,5,6,7,8,9,10], dtype=int)

In [24]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
type(array1)

numpy.ndarray

In [26]:
array1.ndim

1

In [28]:
array1.shape

(10,)

In [33]:
array2=np.array([1,2,3,4,5,6,7,8,9])

In [40]:
reshaping_array =array2.reshape(3,3)

In [42]:
reshaping_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
type(reshaping_array)

numpy.ndarray

In [43]:
reshaping_array.ndim

2

In [44]:
reshaping_array.shape

(3, 3)

In [37]:
array3 = np.array([10,20,30,40,50], dtype=int)

In [38]:
array3

array([10, 20, 30, 40, 50])

In [39]:
array3.shape

(5,)

### Task 2: Important Mathematical Operations

In [ ]:
'''
Given two arrays:

    a = np.array([10,20,30,40])
    b = np.array([1,2,3,4])

Perform and print results for

    addition(a + b)
    Subtraction(A-B)
    Multiplication (A * B)
    division(A/B)
    power(a ** 2)

Extra Use Numpy functions np.add(), np.subtract() for the same operations
'''

In [46]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

In [49]:
a + b


array([11, 22, 33, 44])

In [51]:
a - b

array([ 9, 18, 27, 36])

In [52]:
a * b

array([ 10,  40,  90, 160])

In [53]:
b / a

array([0.1, 0.1, 0.1, 0.1])

In [54]:
a ** 2

array([ 100,  400,  900, 1600])

In [55]:
np.sum(a)

np.int64(100)

In [56]:
np.sum(b)

np.int64(10)

In [58]:
np.subtract(a,b)

array([ 9, 18, 27, 36])

In [59]:
np.multiply(a,b)

array([ 10,  40,  90, 160])

### Task 3: Important Numpy Mathematical Formulas

In [66]:
'''
Given:

    values = np.array([2,4, 6, 8,10])

calculate:

    Square root of each elements
    Exponential of each elements
    natural logarithms of each element
    sum of all elements
    cumulative sum of elements

use numpy functions only
'''

'\nGiven:\n\n    values = np.array([2,4, 6, 8,10])\n\ncalculate:\n\n    Square root of each elements\n    Exponential of each elements\n    natural logarithms of each element\n    sum of all elements\n    cumulative sum of elements\n\nuse numpy functions only\n'

In [67]:
values = np.array([2,4,6,8,10])

In [68]:
values

array([ 2,  4,  6,  8, 10])

In [69]:
np.sqrt(values)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [70]:
np.square(values)

array([  4,  16,  36,  64, 100])

In [71]:
np.exp(values)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04])

In [72]:
np.log(values)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509])

In [73]:
np.sum(values)

np.int64(30)

In [74]:
np.cumsum(values)

array([ 2,  6, 12, 20, 30])

### Task 4: Aggregation operations

In [ ]:
'''
given a 2d Array:

    data = np.array([[10,20,30],[40,50,60],[70,80,90]])

find:

    row wise sum
    column wise sum
    minimum value
    maximum value
    overall mean
'''

In [75]:
data = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [76]:
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
''' row wise sum'''

np.sum(data, axis = 1)

array([ 60, 150, 240])

In [79]:
''' column wise sum'''

np.sum(data, axis = 0)

array([120, 150, 180])

In [80]:
np.min(data)

np.int64(10)

In [81]:
np.max(data)

np.int64(90)

In [82]:
np.mean(data)

np.float64(50.0)

### Task 5: Statistical Operations (Core Focus)

In [ ]:
'''
Given

    marks = np.array([78,85,90,66,72,88,95,60])

Calculate and print:

    Mean
    Median
    Variance
    standard deviation
    minimum, maximum
    range(max - min)
'''

In [83]:
marks = np.array([78,85,90,66,72,88,95,60])

In [84]:
marks

array([78, 85, 90, 66, 72, 88, 95, 60])

In [85]:
np.mean(marks)

np.float64(79.25)

In [86]:
np.median(marks)

np.float64(81.5)

In [87]:
np.var(marks)

np.float64(134.1875)

In [88]:
np.std(marks)

np.float64(11.583932838203095)

In [89]:
np.min(marks)

np.int64(60)

In [90]:
np.max(marks)

np.int64(95)

In [92]:
np.max(marks) - np.min(marks)

np.int64(35)

### Task 6 percentiles and sorting

In [ ]:
'''
Using the same marks arrays:

1 . Sort the array
2. Find:

        25th percentile
        50th percentile
        75th percentile

3. Cont how many students scored above the average marks
'''

In [94]:
marks

array([78, 85, 90, 66, 72, 88, 95, 60])

In [95]:
np.sort(marks)

array([60, 66, 72, 78, 85, 88, 90, 95])

In [96]:
np.percentile(marks, 25)

np.float64(70.5)

In [97]:
np.percentile(marks, 50)

np.float64(81.5)

In [98]:
np.percentile(marks, 75)

np.float64(88.5)

In [107]:
count = 0
mean = np.mean(marks)
for i in marks:
    if i > mean:
        #print(i)
        count += 1
print(count)

4


In [108]:
mean = np.mean(marks)
count = np.sum(marks > mean)
print(count)

4


### Task 7: Mini Use case: Sales Analysis

In [ ]:
'''
Given daily sales data:

    sales = np.array([1200,1500,900,2000,1800,1700,1600])

Perform:

    1. Total Weekly sales
    2. Average daily sales
    3. Highest and lowest sales day
    4. standard deviation of sales
    5. Identify days where sales were above average
'''

In [109]:
 sales = np.array([1200,1500,900,2000,1800,1700,1600])

In [110]:
sales

array([1200, 1500,  900, 2000, 1800, 1700, 1600])

In [111]:
np.sum(sales)

np.int64(10700)

In [112]:
np.mean(sales)

np.float64(1528.5714285714287)

In [113]:
np.max(sales)

np.int64(2000)

In [114]:
np.min(sales)

np.int64(900)

In [115]:
np.std(sales)

np.float64(345.2298849598449)

In [117]:
mean = np.mean(sales)
count = sales[sales > mean]

In [118]:
count

array([2000, 1800, 1700, 1600])